### ISSUE TITLE
Type error on plugin execution

### ISSUE THREAD

**Issue by svjakrm** [benov84/homebridge-tesy-heater#4]
I got next error on plugin execution 
`[12/3/2023, 11:24:34 PM] [heater1] Executing RefreshTesyHeaterStatus
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-tesy-heater-v2/index.js:133:41)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tesy-heater-v2/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tesy-heater-v2/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:514:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tesy-heater-v2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)`
  
  OS: MacOS Ventura 13.6 (Apple M1)
  Node: v20.9.0
  Homebridge: v1.7.0
  Plugin: homebridge-tesy-heater-v2 v4.0.43

**Comment by svjakrm** [comment]
Can you please update the instruction how to get userid and device_id? The old one method doesn't work for me, I can't login to v3 mytesy page and got "invalid credentials" error while trying to access https://www.mytesy.com/v3/api.php?do=get_dev
`{ "login":{"user":"","msg":"Invalid credentials","error":"1"}}`

**Comment by benov84** [comment]
I will see this and update, thanks

**Comment by benov84** [comment]
Hi, you can find the device id this way.
Login at mytesy.com and open your device. Then open browser's Developer Tools. Go to Network tab and you will see requests named "old-app-devices".
Click on them one by one and look at the Response tab on right. You will find the device id inside Json response in field named "id". The device id is 40-symbol long combination of numbers and letters.

**Comment by benov84** [comment]
If you have trouble finding the device id, please reply. I'm closing this issue for now.
About the error you have posted in first comment, I know about it, and I will check it when I have some time. Thanks
